package com.nestor.anotaciones1.entidades;

// default package
// Generated 16 mar 2023 9:55:32 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Autores generated by hbm2java
 */
@Entity
@Table(name = "autores")
public class Autores implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "cod", unique = true, nullable = false, length = 5)
	private String cod;
	@Column(name = "nombre", length = 60)
	private String nombre;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autores")
	private Set<Libros> libroses = new HashSet<Libros>(0);

	public Autores() {
	}

	public Autores(String cod) {
		this.cod = cod;
	}

	public Autores(String cod, String nombre, Set libroses) {
		this.cod = cod;
		this.nombre = nombre;
		this.libroses = libroses;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public Set getLibroses() {
		return this.libroses;
	}

	public void setLibroses(Set libroses) {
		this.libroses = libroses;
	}
	@Override
	public String toString() {
		String resultado = "Código: " + cod + "\nNombre: " + nombre;
		resultado += (libroses.size()>0?"\nHa escrito: ":"\nNo ha escrito ningún libro");
		if(libroses.size()>0) {
			for(Libros l : libroses) {
				resultado += "\n" + l.getTitulo();
			}
		}					
		return resultado;
	}

}


