package com.nestor.springboot.backend.tienda.models.entity;

// default package
// Generated 31 ene 2024 9:54:47 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * DetallePedido generated by hbm2java
 */
@Entity
@Table(name = "detalle_pedido", schema = "public")
public class DetallePedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idDetallePedido;
	private Pedido pedido;
	private Producto producto;
	private Integer cantidad;

	public DetallePedido() {
	}

	public DetallePedido(int idDetallePedido) {
		this.idDetallePedido = idDetallePedido;
	}

	public DetallePedido(int idDetallePedido, Pedido pedido, Producto producto, Integer cantidad) {
		this.idDetallePedido = idDetallePedido;
		this.pedido = pedido;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@Id

	@Column(name = "id_detalle_pedido", unique = true, nullable = false)
	public int getIdDetallePedido() {
		return this.idDetallePedido;
	}

	public void setIdDetallePedido(int idDetallePedido) {
		this.idDetallePedido = idDetallePedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
