package com.nestor.springboot.backend.tienda.models.entity;

import java.time.LocalDate;

// default package
// Generated 31 ene 2024 9:54:47 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", schema = "public")
public class Pedido implements java.io.Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPedido;
	private Usuario usuario;
	private LocalDate fecha;
	@JsonIgnore
	private Set <DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

	public Pedido() {
	}

	public Pedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public Pedido(int idPedido, Usuario usuario, LocalDate fecha, Set <DetallePedido>detallePedidos) {
		this.idPedido = idPedido;
		this.usuario = usuario;
		this.fecha = fecha;
		this.detallePedidos = detallePedidos;
	}

	@Id

	@Column(name = "id_pedido", unique = true, nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public LocalDate getFecha() {
		return this.fecha;
	}

	public void setFecha(LocalDate fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
