package com.nestor.BibliotecaH2.entidades;

// default package
// Generated 15 mar 2023 10:39:43 by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String cod;
	private String nombre;
	private Set<Libros> libroses = new HashSet<Libros>(0);

	public Autores() {
	}

	public Autores(String cod) {
		this.cod = cod;
	}

	public Autores(String cod, String nombre, Set<Libros> libroses) {
		this.cod = cod;
		this.nombre = nombre;
		this.libroses = libroses;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Libros> getLibroses() {
		return this.libroses;
	}

	public void setLibroses(Set<Libros> libroses) {
		this.libroses = libroses;
	}

	@Override
	public String toString() {
		String resultado =  "Código: "  + cod + "\nNombre: " + nombre;
		resultado +=(libroses.size()>0? "\nHa escrito: " : "\nNo ha escrito ningún libro");	
		if(libroses.size()>0) {
		}
		
		for(Libros l : libroses) {
			resultado += "\n" + l.getTitulo();
		}
		
		return resultado;
		}
	

	}
